@WebServiceLayer_HostAddress = https://localhost:5555


GET {{WebServiceLayer_HostAddress}}/api/titles/
Accept: application/json

###

POST {{WebServiceLayer_HostAddress}}/api/titles/
Accept: application/json
Content-Type: application/json
{ 
  "search": "potter radcliff"
}
###

POST {{WebServiceLayer_HostAddress}}/api/titles?page=12&pageSize=5
Accept: application/json
Content-Type: application/json
{ 
  "search": "potter radcliff"
}
###

GET {{WebServiceLayer_HostAddress}}/api/titles?page=2&pageSize=2
Accept: application/json

###

GET {{WebServiceLayer_HostAddress}}/api/titles?search=water
Accept: application/json

###

GET {{WebServiceLayer_HostAddress}}/api/titles?search=water&pageSize=6
Accept: application/json

###


GET {{WebServiceLayer_HostAddress}}/api/titles/tt0081912
Accept: application/json

###

GET {{WebServiceLayer_HostAddress}}/api/titles/ttmadeup100 
Accept: application/json


###

##################################
############# USER ###############
##################################

Post {{WebServiceLayer_HostAddress}}/api/users/create
Accept: application/json
Content-Type: application/json
{ 
  "username": "testuser",
  "password": "testMig1",
  "firstName": "Test",
  "email": "test@email.com"
}

###
Post {{WebServiceLayer_HostAddress}}/api/users/login
Accept: application/json
Content-Type: application/json
{ 
  "username": "testuser",
  "password": "12345678"
}

###
GET {{WebServiceLayer_HostAddress}}/api/users/me
Accept: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU0NDg2NjR9.RhK_0hiGtpt3SNpkbHrIY47DeMqAbBKwlyfQp3c0rg8

###
PUT {{WebServiceLayer_HostAddress}}/api/users/me/changepassword
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU0MDAzNDV9.kmavr-rUJOGPw3WMbFFZIP1dMM5Nkqkp9-04L-6rtH4
{ 
  "oldPassword": "testMig2",
  "newPassword": "abcdefg1",
  "confirmNewPassword": "abcdefg1"
}

###
PUT {{WebServiceLayer_HostAddress}}/api/users/me
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU0MDAzNDV9.kmavr-rUJOGPw3WMbFFZIP1dMM5Nkqkp9-04L-6rtH4
{
  "firstName": "opdateret"
}
###
GET {{WebServiceLayer_HostAddress}}/api/users
Accept: application/json


###
DELETE {{WebServiceLayer_HostAddress}}/api/users/me
Accept: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU0MDAzNDV9.kmavr-rUJOGPw3WMbFFZIP1dMM5Nkqkp9-04L-6rtH4


###

GET {{WebServiceLayer_HostAddress}}/api/users/testuser/ratings
Accept: application/json


#######################################
############# BOOKMARKS ###############
#######################################

###### Titles ######

POST {{WebServiceLayer_HostAddress}}/api/users/me/bookmarks/titles/tt0052520
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU5MDEzNjF9.PUWe3EmV3gEO0xXEYUjBqW2gl3BtlS2y3zrJO37Ry-Q

###
Put {{WebServiceLayer_HostAddress}}/api/users/me/bookmarks/titles/tt0081912
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjUzODU4Mjd9.LZ4R1GPYVIdChDx6FldFy7vsDVao1WUwImuTFk84vWg

 {
  "note": "Den her film SKAL ses + alle de andre"
 }

###
GET {{WebServiceLayer_HostAddress}}/api/users/me/bookmarks/titles
Accept: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU5MDIwNzZ9.zwV8nkdUGeCv1Lq75fhYz02BdUOg3h8nfXzxK-S50Xg

##### Persons #####

###
POST {{WebServiceLayer_HostAddress}}/api/users/me/bookmarks/persons/nm3617946
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU4OTg2MTF9.PWZ1Q3-DVhM8k4eVKKkMoZ8HHgOCuF6l5re0cjua2Tk

###
Put {{WebServiceLayer_HostAddress}}/api/users/me/bookmarks/persons/nm3617946
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjUzODU4Mjd9.LZ4R1GPYVIdChDx6FldFy7vsDVao1WUwImuTFk84vWg
 {
  "note": "kæft en god skuespiller"
 }

###
GET {{WebServiceLayer_HostAddress}}/api/users/me/bookmarks/persons
Accept: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU4OTg2MTF9.PWZ1Q3-DVhM8k4eVKKkMoZ8HHgOCuF6l5re0cjua2Tk

###
DELETE {{WebServiceLayer_HostAddress}}/api/users/me/bookmarks/persons/nm3617946
Accept: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjUzODM5NDd9.2eJiN7N5VnJO7U9p0JxfqEfq-2CXDz4Q5VE6dyH_u6Q


#######################################
############# RATINGS #################
#######################################

### User Ratings ###

###
POST {{WebServiceLayer_HostAddress}}/api/users/me/ratings/tt0063929
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU5MDM2Njl9.WH-Wd32EXEAcbKNU5Tb96kJUxkwwzk3GE9c1xSu80i4
{
  "rating": 9
}
###
GET {{WebServiceLayer_HostAddress}}/api/users/me/ratings/tt0081912
Accept: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU5MDM2Njl9.WH-Wd32EXEAcbKNU5Tb96kJUxkwwzk3GE9c1xSu80i4

###
GET {{WebServiceLayer_HostAddress}}/api/users/me/ratings?page=0&pageSize=8
Accept: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU5MDM2Njl9.WH-Wd32EXEAcbKNU5Tb96kJUxkwwzk3GE9c1xSu80i4

###
DELETE {{WebServiceLayer_HostAddress}}/api/users/me/ratings/tt0081912
Accept: application/json
Authorization: bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJleHAiOjE3NjU5MDM2Njl9.WH-Wd32EXEAcbKNU5Tb96kJUxkwwzk3GE9c1xSu80i4


### Title ####

GET {{WebServiceLayer_HostAddress}}/api/titles/tt0081912/rating
Accept: application/json

###
GET {{WebServiceLayer_HostAddress}}/api/titles/tt0081912/rating/groupedrating
Accept: application/json

### Peron ####

GET {{WebServiceLayer_HostAddress}}/api/people/nm0651451/rating
Accept: application/json

