@WebServiceLayer_HostAddress = https://localhost:5555

GET {{WebServiceLayer_HostAddress}}/api/titles/
Accept: application/json

###

POST {{WebServiceLayer_HostAddress}}/api/titles/
Accept: application/json
Content-Type: application/json
{ 
  "search": "potter radcliff"
}
###

POST {{WebServiceLayer_HostAddress}}/api/titles?page=12&pageSize=5
Accept: application/json
Content-Type: application/json
{ 
  "search": "potter radcliff"
}
###

GET {{WebServiceLayer_HostAddress}}/api/titles?page=2&pageSize=2
Accept: application/json

###

GET {{WebServiceLayer_HostAddress}}/api/titles?search=water
Accept: application/json

###

GET {{WebServiceLayer_HostAddress}}/api/titles?search=water&pageSize=6
Accept: application/json

###


GET {{WebServiceLayer_HostAddress}}/api/titles/tt0081912 
Accept: application/json

###

GET {{WebServiceLayer_HostAddress}}/api/titles/ttmadeup100 
Accept: application/json


###

##################################
############# USER ###############
##################################

Post {{WebServiceLayer_HostAddress}}/api/User
Accept: application/json
Content-Type: application/json
{ 
  "username": "testuser",
  "password": "testMig",
  "firstName": "Test",
  "lastName": "User",
  "email": "test@email.com"
}

###

PUT {{WebServiceLayer_HostAddress}}/api/User
Accept: application/json
Content-Type: application/json
{ 
  "username": "testuser",
  "password": "testMig"
}

###

GET {{WebServiceLayer_HostAddress}}/api/User/testuser
Accept: application/json

###

DELETE {{WebServiceLayer_HostAddress}}/api/User/testuser
Accept: application/json

